"use client";

import { useEffect, useMemo, useRef, useState } from "react";
import { api } from "@/lib/api";
import { buildDesign, ensureDesign } from "@/lib/design";
import type { CopilotAction, CopilotProposal, DesignElement, MediaAsset, Project, Slide, SlideBlueprint, SourceChunk, VisualCatalog } from "@/lib/types";

type Tab = "content" | "design" | "media" | "copilot" | "sources";
const actionLabels: Array<{ action: CopilotAction; label: string; icon: string }> = [
  { action: "shorten", label: "Rút gọn", icon: "↘" }, { action: "simplify", label: "Dễ hiểu hơn", icon: "A" },
  { action: "make_engaging", label: "Sinh động hơn", icon: "✦" }, { action: "generate_question", label: "Tạo câu hỏi", icon: "?" },
  { action: "visual_prompt", label: "Prompt hình", icon: "▣" },
];

function normalizeBullets(items: unknown[]) { return (items || []).map((x) => typeof x === "string" ? x : (x && typeof x === "object" && "text" in x ? String((x as { text: unknown }).text) : String(x ?? ""))); }

export default function Inspector({ draft, blueprint, project, catalog, mediaAssets, selectedElementId, onSelectElement, onChange, onApplyProposal, onRegenerateSection, onProjectThemeChanged, onMediaRefresh, onPersistedSlide, busy }: {
  draft: Slide; blueprint: SlideBlueprint | null; project: Project; catalog: VisualCatalog | null; mediaAssets: MediaAsset[];
  selectedElementId?: string | null; onSelectElement: (id: string | null) => void;
  onChange: (patch: Partial<Slide>) => void; onApplyProposal: (proposal: CopilotProposal) => void; onRegenerateSection: (instruction?: string) => void;
  onProjectThemeChanged: (themeKey: string) => Promise<void>; onMediaRefresh: () => Promise<void>; onPersistedSlide: (slide: Slide) => void; busy: string;
}) {
  const [tab, setTab] = useState<Tab>("content"); const [custom, setCustom] = useState(""); const [proposal, setProposal] = useState<CopilotProposal | null>(null);
  const [copilotBusy, setCopilotBusy] = useState(false); const [mediaBusy, setMediaBusy] = useState(""); const [chunks, setChunks] = useState<Record<string, SourceChunk>>({});
  const fileRef = useRef<HTMLInputElement>(null);
  const bullets = useMemo(() => normalizeBullets(draft.onscreen_text), [draft.onscreen_text]);
  const guidingQuestion = String((draft.ai_metadata || {}).guiding_question || "");
  const projectTheme = String((project.settings || {}).theme_key || "studio_light");
  const design = ensureDesign(catalog, draft.design_json, draft.layout_hint);
  const selectedElement = design.elements?.find((x) => x.id === selectedElementId) || null;
  const attachedIds = new Set((draft.media || []).flatMap((x) => x && typeof x === "object" && "asset_id" in x ? [String((x as { asset_id: unknown }).asset_id)] : []));

  useEffect(() => {
    if (tab !== "sources" || !blueprint) return;
    const missing = blueprint.source_refs.map((x) => x.source_chunk_id).filter((id) => !chunks[id]); if (!missing.length) return;
    Promise.all(missing.map((id) => api.getChunk(id).then((chunk) => [id, chunk] as const).catch(() => null))).then((rows) => setChunks((prev) => { const next = { ...prev }; rows.forEach((row) => { if (row) next[row[0]] = row[1]; }); return next; }));
  }, [tab, blueprint, chunks]);

  const runCopilot = async (action: CopilotAction, instruction?: string) => { setCopilotBusy(true); setProposal(null); try { setProposal(await api.copilot(draft.id, action, instruction)); } catch (e) { setProposal({ mode: "error", action, summary: e instanceof Error ? e.message : "Copilot thất bại", patch: {}, warnings: [] }); } finally { setCopilotBusy(false); } };
  const setBullet = (index: number, value: string) => { const next = [...bullets]; next[index] = value; onChange({ onscreen_text: next }); };
  const patchElement = (id: string, patch: Partial<DesignElement>) => onChange({ design_json: { ...design, elements: (design.elements || []).map((e) => e.id === id ? { ...e, ...patch } : e) } });

  const useLayout = (key: string) => { const layout = catalog?.layouts.find((x) => x.key === key); if (!layout) return; onChange({ layout_hint: key, design_json: buildDesign(layout, design, design.theme_key) }); onSelectElement(null); };
  const setSlideTheme = (key: string | null) => onChange({ design_json: { ...design, theme_key: key } });

  const upload = async (file: File) => { setMediaBusy("Đang tải media…"); try { await api.uploadMedia(project.id, file, draft.id); await onMediaRefresh(); } finally { setMediaBusy(""); if (fileRef.current) fileRef.current.value = ""; } };
  const attach = async (asset: MediaAsset) => { setMediaBusy("Đang gắn media…"); try { const slide = await api.attachMedia(draft.id, asset.id, "visual"); onPersistedSlide(slide); await onMediaRefresh(); } finally { setMediaBusy(""); } };
  const generate = async (kind: "image" | "video") => { const prompt = kind === "image" ? draft.image_prompt : draft.video_prompt; if (!prompt?.trim()) return; setMediaBusy(kind === "image" ? "Đang tạo ảnh…" : "Đang tạo job video…"); try { await api.promptMedia(draft.id, kind, prompt); const bp = await api.getBlueprint(draft.id); onPersistedSlide(bp.slide as Slide); await onMediaRefresh(); } finally { setMediaBusy(""); } };
  const removeAsset = async (asset: MediaAsset) => { if (!confirm(`Xóa media “${asset.original_name || asset.asset_type}”?`)) return; setMediaBusy("Đang xóa media…"); try { await api.deleteMedia(asset.id); await onMediaRefresh(); } finally { setMediaBusy(""); } };

  const tabs: Array<[Tab,string]> = [["content","Nội dung"],["design","Thiết kế"],["media","Media"],["copilot","AI"],["sources","Nguồn"]];
  return <aside className="flex w-[420px] shrink-0 flex-col border-l border-slate-200 bg-white 2xl:w-[460px]">
    <div className="flex h-12 shrink-0 border-b border-slate-200 px-1">{tabs.map(([t,label]) => <button key={t} onClick={() => setTab(t)} className={`relative flex-1 text-[11px] font-bold ${tab === t ? "text-violet-700" : "text-slate-500"}`}>{label}{tab === t && <span className="absolute inset-x-2 bottom-0 h-0.5 rounded-full bg-violet-600" />}</button>)}</div>
    <div className="scrollbar-thin flex-1 overflow-y-auto p-4">
      {tab === "content" && <div className="space-y-5">
        <Field label="Tiêu đề"><input value={draft.title || ""} onChange={(e) => onChange({ title: e.target.value })} className="input" /></Field>
        <Field label="Nội dung trên slide" suffix={`${bullets.length}/7`}><div className="space-y-2">{bullets.map((b,i) => <div key={i} className="flex gap-2"><textarea value={b} rows={2} onChange={(e)=>setBullet(i,e.target.value)} className="input min-h-16 flex-1 resize-none text-xs"/><button onClick={()=>onChange({onscreen_text:bullets.filter((_,j)=>j!==i)})} className="w-8 rounded-xl border text-slate-400">×</button></div>)}<button onClick={()=>onChange({onscreen_text:[...bullets,"Ý mới"]})} className="w-full rounded-xl border border-dashed py-2 text-xs font-bold text-violet-600">+ Thêm ý</button></div></Field>
        <Field label="Lời giảng giáo viên"><textarea value={draft.teacher_script || ""} rows={6} onChange={(e)=>onChange({teacher_script:e.target.value})} className="input resize-y text-xs leading-5"/></Field>
        <Field label="Hoạt động học sinh"><textarea value={draft.student_instruction || ""} rows={3} onChange={(e)=>onChange({student_instruction:e.target.value})} className="input resize-y text-xs leading-5"/></Field>
        <Field label="Câu hỏi dẫn dắt"><textarea value={guidingQuestion} rows={2} onChange={(e)=>onChange({ai_metadata:{...(draft.ai_metadata||{}),guiding_question:e.target.value}})} className="input resize-none text-xs"/></Field>
        <div className="grid grid-cols-2 gap-3"><Field label="Loại visual"><select value={draft.visual_type || ""} onChange={(e)=>onChange({visual_type:e.target.value})} className="input text-xs">{["","hero","photo","educational_illustration","map","diagram","concept_map","infographic","comparison","timeline","quiz_ui","references","video_scene"].map(v=><option key={v} value={v}>{v||"—"}</option>)}</select></Field><Field label="Thời lượng"><input type="number" min={0} value={draft.duration_seconds||0} onChange={(e)=>onChange({duration_seconds:Number(e.target.value)})} className="input text-xs"/></Field></div>
        <Field label="Mô tả visual"><textarea value={draft.visual_description||""} rows={3} onChange={(e)=>onChange({visual_description:e.target.value})} className="input resize-y text-xs"/></Field>
        <Field label="Prompt tạo ảnh"><textarea value={draft.image_prompt||""} rows={4} onChange={(e)=>onChange({image_prompt:e.target.value})} className="input resize-y bg-slate-50 font-mono text-[11px]"/></Field>
        <Field label="Prompt tạo video"><textarea value={draft.video_prompt||""} rows={4} onChange={(e)=>onChange({video_prompt:e.target.value})} className="input resize-y bg-slate-50 font-mono text-[11px]"/></Field>
        <label className="flex items-center justify-between rounded-xl border border-slate-200 p-3"><span className="text-xs font-semibold">Giáo viên duyệt slide</span><input type="checkbox" checked={draft.teacher_approved} onChange={(e)=>onChange({teacher_approved:e.target.checked})} className="h-4 w-4 accent-violet-600"/></label>
      </div>}

      {tab === "design" && <div className="space-y-6">
        <section><Title>Theme</Title><p className="mb-3 text-[11px] leading-5 text-slate-500">Theme dự án: <b>{catalog?.themes.find(x=>x.key===projectTheme)?.name || projectTheme}</b>. Slide có thể ghi đè riêng.</p><div className="grid grid-cols-2 gap-2">{catalog?.themes.map(t=><button key={t.key} onClick={()=>setSlideTheme(t.key)} className={`rounded-xl border p-3 text-left ${design.theme_key===t.key ? "border-violet-500 ring-1 ring-violet-200" : "border-slate-200"}`}><div className="flex gap-1">{[t.tokens.bg,t.tokens.surface,t.tokens.accent].map(c=><span key={c} className="h-5 w-5 rounded-full border" style={{background:c}}/>)}</div><div className="mt-2 text-xs font-black">{t.name}</div><div className="mt-1 line-clamp-2 text-[10px] text-slate-400">{t.description}</div></button>)}</div><div className="mt-2 grid grid-cols-2 gap-2"><button onClick={()=>setSlideTheme(null)} className="rounded-xl border py-2 text-[11px] font-bold">Dùng theme dự án</button><button onClick={()=>onProjectThemeChanged(design.theme_key || projectTheme)} className="rounded-xl bg-slate-900 py-2 text-[11px] font-bold text-white">Đặt làm mặc định</button></div></section>
        <section><Title>Layout</Title><div className="grid grid-cols-2 gap-2">{catalog?.layouts.map(l=><button key={l.key} onClick={()=>useLayout(l.key)} className={`rounded-xl border p-3 text-left ${design.layout_key===l.key ? "border-violet-500 bg-violet-50" : "border-slate-200"}`}><div className="text-xs font-black">{l.name}</div><div className="mt-1 text-[10px] leading-4 text-slate-400">{l.description}</div></button>)}</div></section>
        <section><div className="flex items-center justify-between"><Title>Vùng nội dung</Title><span className="text-[10px] text-slate-400">Kéo trực tiếp trên canvas</span></div><div className="space-y-2">{(design.elements||[]).filter(e=>e.type!=="overlay").map(el=><button key={el.id} onClick={()=>onSelectElement(el.id)} className={`flex w-full items-center justify-between rounded-xl border px-3 py-2 text-left text-xs ${selectedElementId===el.id ? "border-violet-400 bg-violet-50" : "border-slate-200"}`}><span className="font-bold capitalize">{el.type}</span><span className="text-[10px] text-slate-400">{Math.round(el.x)},{Math.round(el.y)} · {Math.round(el.w)}×{Math.round(el.h)}</span></button>)}</div>
          {selectedElement && <div className="mt-3 rounded-2xl border border-violet-100 bg-violet-50 p-3"><div className="mb-3 text-xs font-black text-violet-800">Đang chọn: {selectedElement.type}</div><div className="grid grid-cols-4 gap-2">{(["x","y","w","h"] as const).map(k=><label key={k} className="text-[10px] font-bold uppercase text-slate-500">{k}<input type="number" min={0} max={100} value={selectedElement[k]} onChange={(e)=>patchElement(selectedElement.id,{[k]:Math.max(0,Math.min(100,Number(e.target.value)))} as Partial<DesignElement>)} className="mt-1 w-full rounded-lg border border-violet-100 bg-white px-2 py-1.5 text-xs"/></label>)}</div><div className="mt-3 grid grid-cols-2 gap-2"><button onClick={()=>patchElement(selectedElement.id,{locked:!selectedElement.locked})} className="rounded-lg bg-white py-2 text-[11px] font-bold">{selectedElement.locked?"🔓 Mở khóa":"🔒 Khóa"}</button><button onClick={()=>patchElement(selectedElement.id,{visible:selectedElement.visible===false})} className="rounded-lg bg-white py-2 text-[11px] font-bold">{selectedElement.visible===false?"👁 Hiện":"◌ Ẩn"}</button></div></div>}
        </section>
      </div>}

      {tab === "media" && <div className="space-y-5">
        <div className="rounded-2xl border border-violet-100 bg-violet-50 p-4"><div className="text-sm font-black text-violet-900">Media Workspace</div><div className="mt-1 text-xs leading-5 text-violet-700">Upload ảnh/video hoặc sinh media từ prompt của slide. Media được lưu độc lập để có thể tái sử dụng.</div></div>
        <input ref={fileRef} type="file" className="hidden" accept="image/*,video/*,audio/*,.pdf,.svg" onChange={(e)=>{const f=e.target.files?.[0]; if(f) upload(f).catch(()=>setMediaBusy(""));}}/><button onClick={()=>fileRef.current?.click()} disabled={!!mediaBusy} className="w-full rounded-xl border border-dashed border-violet-300 bg-violet-50 py-3 text-xs font-bold text-violet-700">＋ Upload media</button>
        <div className="grid grid-cols-2 gap-2"><button disabled={!draft.image_prompt?.trim()||!!mediaBusy} onClick={()=>generate("image")} className="rounded-xl bg-violet-600 p-3 text-left text-white disabled:opacity-40"><div className="text-lg">🖼️</div><div className="mt-1 text-xs font-bold">Sinh ảnh từ prompt</div></button><button disabled={!draft.video_prompt?.trim()||!!mediaBusy} onClick={()=>generate("video")} className="rounded-xl bg-slate-900 p-3 text-left text-white disabled:opacity-40"><div className="text-lg">🎬</div><div className="mt-1 text-xs font-bold">Tạo job video</div></button></div>
        {mediaBusy && <div className="rounded-xl bg-amber-50 p-3 text-xs font-semibold text-amber-700">{mediaBusy}</div>}
        <div><div className="mb-2 flex items-center justify-between"><Title>Thư viện media</Title><span className="text-[10px] text-slate-400">{mediaAssets.length} assets</span></div>{!mediaAssets.length && <Empty text="Chưa có media. Upload hoặc sinh từ prompt."/>}<div className="grid grid-cols-2 gap-3">{mediaAssets.map(a=><div key={a.id} className="overflow-hidden rounded-xl border border-slate-200 bg-white"><div className="flex aspect-video items-center justify-center bg-slate-100">{a.status==="ready"&&a.asset_type==="image"?<img src={api.mediaUrl(a.id)} className="h-full w-full object-cover" alt="media"/>:<div className="text-center"><div className="text-2xl">{a.asset_type==="video"?"🎬":a.asset_type==="audio"?"🎧":"🖼️"}</div><div className="mt-1 text-[9px] font-bold uppercase text-slate-400">{a.status}</div></div>}</div><div className="p-2"><div className="truncate text-[10px] font-bold">{a.original_name||`${a.asset_type} · ${a.provider||"prompt"}`}</div>{a.prompt&&<div className="mt-1 line-clamp-2 text-[9px] leading-4 text-slate-400">{a.prompt}</div>}<div className="mt-2 flex gap-1"><button onClick={()=>attach(a)} className={`flex-1 rounded-lg py-1.5 text-[9px] font-bold ${attachedIds.has(a.id)?"bg-emerald-50 text-emerald-700":"bg-violet-50 text-violet-700"}`}>{attachedIds.has(a.id)?"✓ Đã gắn":"Gắn vào slide"}</button><button onClick={()=>removeAsset(a)} className="rounded-lg bg-rose-50 px-2 text-[10px] text-rose-600">×</button></div></div></div>)}</div></div>
      </div>}

      {tab === "copilot" && <div><div className="rounded-2xl border border-violet-100 bg-violet-50 p-4"><div className="text-sm font-black text-violet-900">AI Copilot</div><div className="mt-1 text-xs leading-5 text-violet-700">AI chỉ trả đề xuất; giáo viên quyết định có áp dụng hay không.</div></div><div className="mt-4 grid grid-cols-2 gap-2">{actionLabels.map(({action,label,icon})=><button disabled={copilotBusy} key={action} onClick={()=>runCopilot(action)} className="rounded-xl border border-slate-200 p-3 text-left hover:border-violet-300 hover:bg-violet-50 disabled:opacity-50"><div className="text-lg font-black text-violet-600">{icon}</div><div className="mt-1 text-xs font-bold">{label}</div></button>)}</div><div className="mt-4"><textarea value={custom} onChange={(e)=>setCustom(e.target.value)} rows={6} placeholder="Yêu cầu riêng cho slide hoặc toàn section. Có thể ghi rõ: Slide 1: … / Slide 2: …" className="input resize-none text-xs"/><button disabled={copilotBusy||!custom.trim()} onClick={()=>runCopilot("custom",custom)} className="mt-2 w-full rounded-xl bg-slate-900 py-2.5 text-xs font-bold text-white disabled:opacity-40">{copilotBusy?"AI đang đề xuất…":"Gửi Copilot cho slide hiện tại"}</button><div className="mt-2 text-[10px] leading-4 text-slate-400">Nút “Tạo lại toàn bộ section” bên dưới sẽ dùng chính yêu cầu trong ô này và thay toàn bộ slide của section.</div></div>{proposal&&<div className="mt-5 rounded-2xl border border-slate-200 bg-slate-50 p-4"><div className="text-xs font-black uppercase tracking-wider text-slate-500">Bản đề xuất</div><div className="mt-2 text-xs leading-5 text-slate-700">{proposal.summary}</div>{proposal.warnings?.length>0&&<div className="mt-2 rounded-lg bg-amber-50 p-2 text-[11px] text-amber-700">{proposal.warnings.join(" · ")}</div>}<pre className="scrollbar-thin mt-3 max-h-64 overflow-auto whitespace-pre-wrap rounded-xl bg-white p-3 text-[10px] leading-5 text-slate-600">{JSON.stringify(proposal.patch,null,2)}</pre><button disabled={!Object.keys(proposal.patch||{}).length} onClick={()=>{onApplyProposal(proposal);setProposal(null);}} className="mt-3 w-full rounded-xl bg-violet-600 py-2.5 text-xs font-bold text-white disabled:opacity-40">Áp dụng vào bản nháp</button></div>}<button disabled={!!busy} onClick={()=>onRegenerateSection(custom.trim() || undefined)} className="mt-6 w-full rounded-xl border border-rose-200 bg-rose-50 py-2.5 text-xs font-bold text-rose-700">Tạo lại toàn bộ section theo yêu cầu</button></div>}

      {tab === "sources" && <div className="space-y-5"><div><div className="mb-2 flex items-center justify-between"><Title>Nguồn chứng minh</Title><span className="text-[10px] text-slate-400">{blueprint?.source_refs.length||0} refs</span></div>{!blueprint?.source_refs.length&&<Empty text="Slide này chưa có source refs."/>}<div className="space-y-3">{blueprint?.source_refs.map((ref,i)=>{const chunk=chunks[ref.source_chunk_id];return <div key={ref.id} className="rounded-xl border border-slate-200 p-3"><div className="text-[10px] font-black uppercase tracking-wider text-violet-600">Nguồn {i+1}</div>{ref.claim_text&&<div className="mt-1 text-xs font-semibold leading-5">“{ref.claim_text}”</div>}{chunk?<><div className="mt-2 text-[10px] text-slate-400">{chunk.heading||"Không có heading"}{chunk.page_start?` · Trang ${chunk.page_start}${chunk.page_end&&chunk.page_end!==chunk.page_start?`–${chunk.page_end}`:""}`:""}</div><div className="mt-2 line-clamp-6 whitespace-pre-wrap text-[11px] leading-5 text-slate-500">{chunk.content}</div></>:<div className="mt-2 text-[11px] text-slate-400">Đang tải…</div>}</div>})}</div></div><div><div className="mb-2 flex items-center justify-between"><Title>Quiz / Tương tác</Title><span className="text-[10px] text-slate-400">{blueprint?.interactions.length||0} câu</span></div>{!blueprint?.interactions.length&&<Empty text="Slide này chưa có tương tác."/>}<div className="space-y-3">{blueprint?.interactions.map((q,i)=><div key={q.id} className="rounded-xl border border-slate-200 p-3"><div className="flex items-center justify-between"><span className="text-[10px] font-black uppercase text-emerald-600">Câu {i+1}</span><span className="text-[10px] text-slate-400">{q.difficulty||"—"}</span></div><div className="mt-2 text-xs font-bold leading-5">{q.question}</div>{Array.isArray(q.options)&&q.options.length>0&&<div className="mt-2 space-y-1">{q.options.map((o,j)=><div key={j} className="rounded-lg bg-slate-50 px-2 py-1.5 text-[11px] text-slate-600">{String(o)}</div>)}</div>}<div className="mt-2 text-[10px] text-emerald-700">Đáp án: {JSON.stringify(q.correct_answer)}</div></div>)}</div></div></div>}
    </div>
  </aside>;
}

function Field({label,suffix,children}:{label:string;suffix?:string;children:React.ReactNode}){return <label className="block"><div className="mb-2 flex items-center justify-between text-xs font-bold text-slate-600"><span>{label}</span>{suffix&&<span className="text-[10px] font-medium text-slate-400">{suffix}</span>}</div>{children}</label>}
function Title({children}:{children:React.ReactNode}){return <h3 className="text-xs font-black uppercase tracking-wider text-slate-500">{children}</h3>}
function Empty({text}:{text:string}){return <div className="rounded-xl border border-dashed border-slate-300 p-5 text-center text-xs text-slate-400">{text}</div>}
